#!/bin/sh
# This is a chroot wrapper to make sure qemu-*-static are
# inside the chroot.

# We cannot install qemu-user-static from the target repo because
# it will pull the target arch packages.

# echo $@
ROOT=$1

# echo "Root is $ROOT"

if stat -t /usr/bin/qemu-*-static > /dev/null 2>&1; then
    for i in /usr/bin/qemu-*-static; do
	if [ ! -x $ROOT/$i ]; then
	    cp $i $ROOT/$i
	fi
    done
fi

exec /usr/sbin/chroot "$@"
